const $=id=>document.getElementById(id);
const fmt0=n=>Math.round(Number(n||0)).toLocaleString('zh-TW');
const fmt2=n=>Number(n||0).toLocaleString('zh-TW',{minimumFractionDigits:2,maximumFractionDigits:2});
let state={data:null,viewMonth:'',offset:0,version:'0',monthCache:new Map(),syncTimer:null,tick:null,breakTick:null,recentTab:'advance',busyTimer:null,animationMilestone:0,pushMilestone:0,badgeValue:null,sparkMinute:-1};

function localDate(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function now(){return new Date(Date.now()+state.offset)}
function td(date,time){if(!date||!time)return null;const [y,m,d]=date.split('-').map(Number),[h,mi,s=0]=String(time).split(':').map(Number);return new Date(y,m-1,d,h,mi,s)}
function dur(sec){sec=Math.max(0,Math.floor(sec||0));return [Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(x=>String(x).padStart(2,'0')).join(':')}
function hoursText(h){const m=Math.round(Number(h||0)*60);return `${Math.floor(m/60)} 小時 ${String(m%60).padStart(2,'0')} 分`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activeShift(log){if(log?.amStart&&!log.amEnd&&log.amStatus!=='請假')return{name:'上午',start:log.amStart};if(log?.pmStart&&!log.pmEnd&&log.pmStatus!=='請假')return{name:'下午',start:log.pmStart};return null}
function timeMin(t){const p=String(t||'').slice(0,5).split(':').map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:0}
function effectiveLiveSeconds(log){
  const a=activeShift(log);if(!a||!state.data)return 0;
  const settings=state.data.settings||{},dayStart=timeMin(settings.scheduledStart||'11:00'),dayEnd=timeMin(settings.scheduledEnd||'18:00');
  const n=now(),nowMin=n.getHours()*60+n.getMinutes()+n.getSeconds()/60;
  if(a.name==='上午'){
    const from=dayStart,to=Math.min(dayEnd,nowMin);
    return Math.max(0,Math.floor((to-from)*60));
  }
  let from;
  if(log.breakEnd)from=timeMin(log.breakEnd);
  else from=Math.floor(timeMin(log.pmStart)/60)*60;
  const to=Math.min(dayEnd,nowMin);
  return Math.max(0,Math.floor((to-from)*60));
}
function elapsed(log){return effectiveLiveSeconds(log)}
function totals(){const d=state.data;if(!d)return{sec:0,live:0,today:0,month:0,adv:0,bud:0,available:0};const sec=effectiveLiveSeconds(d.today),live=sec*d.settings.hourlyRate/3600,base=d.monthLogs.reduce((s,r)=>s+Number(r.pay||0),0),adv=(d.monthAdvances||[]).reduce((s,r)=>s+Number(r.amount||0),0),bud=(d.monthBudgets||[]).reduce((s,r)=>s+Number(r.amount||0),0),today=Number(d.today.pay||0)+live,month=base+live;return{sec,live,today,month,adv,bud,available:month-adv-bud}}
function status(log){const a=activeShift(log);if(a)return{txt:`工作中・${a.name}`,live:true};if(log?.dayStatus==='全天請假')return{txt:'全天請假'};if(log?.dayStatus==='休假')return{txt:'今日休假'};if(log?.amStart&&log.amEnd&&log.pmStart&&log.pmEnd)return{txt:'今日完成'};if(log?.amEnd&&!log.pmStart)return{txt:'休息中'};return{txt:'未上班'}}
function nextAction(log){if(['全天請假','休假'].includes(log.dayStatus))return'none';if(!log.amStart&&log.amStatus!=='請假')return'am-in';if(!log.amEnd&&log.amStatus!=='請假')return'am-out';if(!log.pmStart&&log.pmStatus!=='請假')return'pm-in';if(!log.pmEnd&&log.pmStatus!=='請假')return'pm-out';return'none'}
function greeting(){const h=now().getHours();return h<11?'早安 👋':h<17?'午安 👋':'晚安 👋'}
function paydayInfo(){const d=state.data.settings.payday,n=now(),p=new Date(n.getFullYear(),n.getMonth(),d);if(n.getDate()>=d)p.setMonth(p.getMonth()+1);const base=new Date(n.getFullYear(),n.getMonth(),n.getDate());return{days:Math.ceil((p-base)/86400000),date:`${p.getMonth()+1}/${p.getDate()} 發薪`}}

function setSync(label,ok=true){$('syncState').innerHTML=`<i class="status-dot"></i>${label}`;$('syncState').style.color=ok?'var(--green)':'var(--red)';$('lastSync').textContent=new Date().toLocaleTimeString('zh-TW',{hour12:false})}
function toast(msg){const el=$('toast');el.textContent='✓ '+msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800)}
window.toast=toast;
function showBusy(title='處理中…',text='請稍後'){clearTimeout(state.busyTimer);state.busyTimer=setTimeout(()=>{$('busyTitle').textContent=title;$('busyText').textContent=text;$('busy').classList.add('show')},220)}
window.showBusy=showBusy;
function hideBusy(){clearTimeout(state.busyTimer);$('busy').classList.remove('show')}
window.hideBusy=hideBusy;
async function call(action,payload={},busy=null){if(busy)showBusy(busy.title,busy.text);try{const r=await GQ_API.call(action,payload);if(r?.version)state.version=r.version;setSync('已同步');return r}catch(e){setSync('同步失敗',false);showError(e.message||String(e));throw e}finally{if(busy)hideBusy()}}
function showError(msg){showModal('操作未完成',`<div class="notice" style="border-color:#6b2e34;color:#ff9ca3">${esc(msg)}</div><button class="primary wide" onclick="closeModal()">知道了</button>`)}

async function boot(){registerSW();bindNav();bindActions();try{const r=await call('getAppData',{});state.data=r;state.viewMonth=r.viewMonth;state.version=r.version||'0';state.offset=new Date(r.serverNow).getTime()-Date.now();state.monthCache.set(r.viewMonth,(r.monthLogs||[]).slice());state.animationMilestone=0;state.pushMilestone=0;renderAll();scheduleSync();window.GQ_NOTIFICATIONS?.init(()=>state);setTimeout(()=>{$('splash').classList.add('hidden');$('app').classList.remove('hidden');$('mobileNav').classList.remove('hidden')},650);if(breakActive())setTimeout(showBreakCountdown,850)}catch(e){$('splash').classList.add('hidden');$('app').classList.remove('hidden');$('mobileNav').classList.remove('hidden');showError('無法載入資料。請確認 API 網址與部署設定。')}}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.data){state.animationMilestone=0;renderLive()}});

function renderAll(){clearInterval(state.tick);renderStatic();renderLive();state.tick=setInterval(renderLive,1000)}
function renderStatic(){const d=state.data,s=status(d.today),p=paydayInfo();$('greeting').textContent=greeting();$('todayText').textContent=now().toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'});$('workBadge').textContent=s.txt;$('workBadge').style.color=s.live?'var(--green)':'#abc0cd';$('perSecond').textContent=`+$${(d.settings.hourlyRate/3600).toFixed(4)} / 秒`;$('goalText').textContent=`目標 $${fmt0(d.settings.monthlyGoal)}`;$('paydayDays').textContent=p.days;$('paydayDate').textContent=p.date;$('hourlyRateLabel').textContent=fmt0(d.settings.hourlyRate);renderTimeline();renderTodayDetail();renderCalendarPair();renderLists();renderStats();renderSettings();renderSpark();updateClockButtons();renderBreakStrip()}
function renderLive(){
  if(!state.data)return;
  const t=totals();
  $('todayIncome').textContent=fmt2(t.today);$('shiftIncome').textContent=fmt2(t.live);$('monthIncome').textContent=fmt2(t.month);$('availableIncome').textContent=fmt0(t.available);$('liveTimer').textContent=dur(t.sec);
  $('deductText').textContent=`收入 $${fmt0(t.month)} − 預支 $${fmt0(t.adv)} − 支出 $${fmt0(t.bud)}`;
  const goal=Math.max(1,Number(state.data.settings.monthlyGoal||1));$('goalProgress').style.width=Math.min(100,t.month/goal*100)+'%';$('availableProgress').style.width=Math.min(100,Math.max(0,t.available/goal*100))+'%';$('shiftProgress').style.width=Math.min(100,(t.sec/3600)/4*100)+'%';
  $('todayPayStatic').textContent=fmt2(t.today);const liveHours=Number(state.data.today.totalHours||0)+t.sec/3600;$('todayHours').textContent=hoursText(liveHours);
  updateMilestones(t.today);updateAppBadge(t.today);const sm=Math.floor(t.sec/60);if(sm!==state.sparkMinute){state.sparkMinute=sm;renderSpark()}
  if(breakActive())renderBreakStrip();
}

function updateMilestones(todayPay){
  const anim=Math.floor(Number(todayPay||0)/100)*100;
  if(anim>=100 && anim!==state.animationMilestone){state.animationMilestone=anim;showMilestoneAnimation(anim)}
  const push=Math.floor(Number(todayPay||0)/200)*200;
  if(push>=200 && push!==state.pushMilestone){state.pushMilestone=push;window.GQ_NOTIFICATIONS?.notifyPayMilestone?.(push)}
}
function showMilestoneAnimation(amount){
  let el=$('milestoneFx');if(!el){el=document.createElement('div');el.id='milestoneFx';el.className='milestone-fx';document.body.appendChild(el)}
  el.innerHTML=`<div class="milestone-burst"><img src="./assets/logo.svg" alt=""><small>今日收入突破</small><strong>$${fmt0(amount)}</strong><span>${amount>=1000?'今天很有成果，繼續保持 ✨':'每一段努力都正在累積 💚'}</span></div>`;
  el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2400);
}
async function updateAppBadge(todayPay){
  if(!('setAppBadge' in navigator))return;const value=Math.max(0,Math.floor(Number(todayPay||0)));if(value===state.badgeValue)return;state.badgeValue=value;
  try{if(value>0)await navigator.setAppBadge(value);else if('clearAppBadge'in navigator)await navigator.clearAppBadge()}catch(_e){}
}

function renderTimeline(){const d=state.data.today,a=nextAction(d);const steps=[['am-in','上午上班',d.amStart,'▣'],['am-out','上午下班',d.amEnd,'☕'],['break','休息中',d.breakEnd&& !d.pmStart?d.breakEnd:'','☕'],['pm-in','下午上班',d.pmStart,'▣'],['pm-out','下午下班',d.pmEnd,'◧']];$('timeline').innerHTML=steps.map(([k,label,time,icon])=>{let done=!!time,current=false;if(k==='break'){done=!!d.breakEnd&&!!d.pmStart;current=!!d.breakEnd&&!d.pmStart}else current=a===k;return`<div class="time-step ${done?'done':''} ${current?'current':''}"><div class="circle">${icon}</div><b>${label}</b><span>${time?time.slice(0,5):'--:--'}</span></div>`}).join('')}
function renderTodayDetail(){const d=state.data.today;const rows=[['上午',d.amStart,d.amEnd,d.amHours],['休息',d.breakStart,d.breakEnd,d.breakMinutes/60],['下午',d.pmStart,d.pmEnd,d.pmHours]];$('todayDetail').innerHTML=rows.map(([name,s,e,h])=>`<div class="detail-row"><b>${name}</b><span>${s?s.slice(0,5):'--:--'} - ${e?e.slice(0,5):'--:--'}</span><small>${name==='休息'?hoursText(h):h?hoursText(h):'—'}</small></div>`).join('')}
function updateClockButtons(){const n=nextAction(state.data.today),inBtn=$('clockInBtn'),outBtn=$('clockOutBtn');inBtn.disabled=!['am-in','pm-in'].includes(n);outBtn.disabled=!['am-out','pm-out'].includes(n);inBtn.style.opacity=inBtn.disabled?.4:1;outBtn.style.opacity=outBtn.disabled?.4:1}
function renderSpark(){
  const el=$('incomeSpark');if(!el||!state.viewMonth)return;
  const [y,m]=state.viewMonth.split('-').map(Number),days=new Date(y,m,0).getDate(),map=new Map((state.data.monthLogs||[]).map(r=>[r.date,Number(r.totalHours||0)]));
  const todayKey=localDate(now()),t=totals();
  if(todayKey.startsWith(state.viewMonth) && state.data.today?.date===todayKey)map.set(todayKey,Number(state.data.today.totalHours||0)+t.sec/3600);
  const vals=[];for(let d=1;d<=days;d++){const key=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;vals.push(Math.max(0,Math.min(6,Number(map.get(key)||0))))}
  const pts=vals.map((v,i)=>`${i/(Math.max(1,vals.length-1))*100},${48-(v/6)*40}`).join(' ');
  const dots=vals.map((v,i)=>`<circle cx="${i/(Math.max(1,vals.length-1))*100}" cy="${48-(v/6)*40}" r=".85" fill="${v>0?'#25e58b':'#355060'}"/>`).join('');
  el.innerHTML=`<svg viewBox="0 0 100 52" preserveAspectRatio="none"><line x1="0" y1="8" x2="100" y2="8" stroke="#1b3b48" stroke-width=".5" stroke-dasharray="2 2"/><polyline points="${pts}" fill="none" stroke="#25e58b" stroke-width="1.7"/>${dots}</svg><div class="spark-scale"><span>6h</span><span>0h</span></div>`;
}

function calendarHTML(month,logs){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),today=localDate(now());let h=['日','一','二','三','四','五','六'].map(x=>`<div class="weekday">${x}</div>`).join('');for(let i=0;i<first.getDay();i++)h+='<div></div>';for(let day=1;day<=last.getDate();day++){const key=`${y}-${String(m).padStart(2,'0')}-${String(day).padStart(2,'0')}`,r=logs.find(x=>x.date===key);let kind='';if(r){if(r.dayStatus==='全天請假')kind='full';else if(['上午請假','下午請假'].includes(r.dayStatus))kind='half';else if(r.dayStatus==='休假')kind='off';else if(r.totalHours>0||r.amStart||r.pmStart)kind='work'}h+=`<button class="calendar-day ${key===today?'today':''}" data-date="${key}">${day}${kind?`<i class="mark ${kind}"></i>`:''}</button>`}return h}
function renderCalendarPair(){
  const logs=state.data.monthLogs||[],title=state.viewMonth.replace('-',' 年 ')+' 月';
  if($('homeMonthTitle'))$('homeMonthTitle').textContent=title;if($('monthTitle'))$('monthTitle').textContent=title;
  if($('homeCalendar'))$('homeCalendar').innerHTML=calendarHTML(state.viewMonth,logs);if($('calendarGrid'))$('calendarGrid').innerHTML=calendarHTML(state.viewMonth,logs);
  document.querySelectorAll('#homeCalendar .calendar-day[data-date]').forEach(b=>b.onclick=()=>openDay(b.dataset.date));
  document.querySelectorAll('#calendarGrid .calendar-day[data-date]').forEach(b=>b.onclick=()=>jumpToWorkDay(b.dataset.date));
}
function jumpToWorkDay(date){const el=document.getElementById('workday-'+date);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),1400)}else openDay(date)}
async function moveMonth(n){const [y,m]=state.viewMonth.split('-').map(Number),d=new Date(y,m-1+n,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(state.monthCache.has(key)){state.viewMonth=key;state.data.viewMonth=key;state.data.monthLogs=state.monthCache.get(key).slice();renderAll();return}showBusy('載入月份資料…','正在整理工時紀錄');try{const r=await GQ_API.call('getMonthData',{viewMonth:key});state.viewMonth=r.viewMonth;state.data.viewMonth=r.viewMonth;state.data.monthLogs=r.monthLogs||[];state.monthCache.set(r.viewMonth,(r.monthLogs||[]).slice());state.version=r.version||state.version;renderAll();setSync('已同步')}catch(e){showError(e.message)}finally{hideBusy()}}

function renderLists(){
  const d=state.data,t=totals();$('advanceTotalPage').textContent=fmt0(t.adv);$('advanceAvailable').textContent=fmt0(t.available);$('budgetTotalPage').textContent=fmt0(t.bud);$('unpaidCount').textContent=(d.monthBudgets||[]).filter(x=>x.status!=='已繳').length+' 筆';
  $('workList').innerHTML=(d.monthLogs||[]).length?d.monthLogs.slice().reverse().map(r=>`<div class="work-day-card" id="workday-${r.date}" data-date="${r.date}"><div class="work-day-head"><div><b>${r.date}</b><span class="day-status">${esc(r.dayStatus)}</span></div><strong class="green">$${fmt0(r.pay)}</strong></div><div class="work-day-grid"><div><small>上午原始紀錄</small><b>${short(r.amStart)}－${short(r.amEnd)}</b><span>計薪 ${hoursText(r.amHours)}</span></div><div><small>休息</small><b>${short(r.breakStart)}－${short(r.breakEnd)}</b><span>${Number(r.breakMinutes||0)} 分鐘</span></div><div><small>下午原始紀錄</small><b>${short(r.pmStart)}－${short(r.pmEnd)}</b><span>計薪 ${hoursText(r.pmHours)}</span></div></div><div class="work-day-foot"><span>有效總工時 <b>${hoursText(r.totalHours)}</b></span><button class="pill-btn">查看／編輯</button></div></div>`).join(''):'<div class="notice">這個月份尚無紀錄。</div>';
  document.querySelectorAll('#workList .work-day-card').forEach(x=>x.onclick=()=>openDay(x.dataset.date));
  $('advanceList').innerHTML=(d.recentAdvances||[]).length?d.recentAdvances.map(r=>`<div class="record-item"><div><b>${r.date}</b><small>${esc(r.note||'未填備註')}</small></div><div><b class="red">-$${fmt0(r.amount)}</b><small><button class="pill-btn" onclick="deleteAdvance(${r.rowId})">刪除</button></small></div></div>`).join(''):'<div class="notice">目前沒有預支紀錄。</div>';
  $('budgetList').innerHTML=(d.budgets||[]).length?d.budgets.map(r=>`<div class="record-item"><div><b>${esc(r.category)} ${r.status==='已繳'?'✓':''}</b><small>${esc(r.note||'無備註')}・${esc(r.status)}</small></div><div><b class="amber">$${fmt0(r.amount)}</b><small><button class="pill-btn" onclick="toggleBudget(${r.rowId},${r.status!=='已繳'})">${r.status==='已繳'?'改未繳':'標已繳'}</button> <button class="pill-btn" onclick="deleteBudget(${r.rowId})">刪除</button></small></div></div>`).join(''):'<div class="notice">目前沒有支出規劃。</div>';renderRecentHome()
}
function renderRecentHome(){const d=state.data,arr=state.recentTab==='advance'?(d.recentAdvances||[]).slice(0,4):(d.budgets||[]).slice(0,4);$('recentHomeList').innerHTML=arr.length?arr.map(r=>state.recentTab==='advance'?`<div class="compact-item"><div><b>${r.date}</b><small>${esc(r.note||'未填備註')}</small></div><b>$${fmt0(r.amount)}</b></div>`:`<div class="compact-item"><div><b>${esc(r.category)}</b><small>${esc(r.status)}</small></div><b>$${fmt0(r.amount)}</b></div>`).join(''):'<div class="notice">目前沒有紀錄。</div>'}
function short(t){return t?t.slice(0,5):'--:--'}

function renderStats(){const logs=state.data.monthLogs||[],t=totals(),h=logs.reduce((s,r)=>s+Number(r.totalHours||0),0)+t.sec/3600,days=logs.filter(r=>r.totalHours>0).length;$('statsMonth').textContent=state.viewMonth;$('statIncome').textContent='$'+fmt2(t.month);$('statHours').textContent=h.toFixed(2)+' 小時';$('statAvg').textContent='$'+fmt0(days?t.month/days:0);$('statDays').textContent=days+' 天';const vals=logs.map(r=>Number(r.pay||0)),mx=Math.max(1,...vals);$('incomeChart').innerHTML=`<div style="height:100%;display:flex;align-items:end;gap:5px">${vals.map((v,i)=>`<div title="${logs[i]?.date} $${fmt0(v)}" style="flex:1;min-width:3px;height:${Math.max(2,v/mx*100)}%;border-radius:5px 5px 1px 1px;background:linear-gradient(#25e58b,#0b6040)"></div>`).join('')}</div>`;const normal=logs.filter(r=>r.totalHours>0&&!String(r.dayStatus).includes('請假')).length,half=logs.filter(r=>['上午請假','下午請假'].includes(r.dayStatus)).length,full=logs.filter(r=>r.dayStatus==='全天請假').length,off=logs.filter(r=>r.dayStatus==='休假').length;$('attendanceStats').innerHTML=[['正常上班',normal],['半天請假',half],['全天請假',full],['休假',off]].map(x=>`<div class="stat-line"><span>${x[0]}</span><b>${x[1]} 天</b></div>`).join('');const weeks={};logs.forEach(r=>{const w=Math.ceil(Number(r.date.slice(-2))/7);weeks[w]??={h:0,p:0};weeks[w].h+=Number(r.totalHours||0);weeks[w].p+=Number(r.pay||0)});$('weeklyStats').innerHTML=Object.keys(weeks).map(w=>`<div class="record-item"><b>第 ${w} 週</b><span>${weeks[w].h.toFixed(2)} 小時・<b class="green">$${fmt0(weeks[w].p)}</b></span></div>`).join('')||'<div class="notice">尚無資料。</div>'}
function renderSettings(){const s=state.data.settings;$('setRate').value=s.hourlyRate;$('setPayday').value=s.payday;$('setGoal').value=s.monthlyGoal;$('setSync').value=s.syncSeconds;$('setBreak').value=s.defaultBreakMinutes;$('setStart').value=s.scheduledStart;$('setEnd').value=s.scheduledEnd}

function bindNav(){
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));
  if($('homePrev'))$('homePrev').onclick=()=>moveMonth(-1);if($('homeNext'))$('homeNext').onclick=()=>moveMonth(1);if($('prevMonth'))$('prevMonth').onclick=()=>moveMonth(-1);if($('nextMonth'))$('nextMonth').onclick=()=>moveMonth(1);
  if($('todayMonth'))$('todayMonth').onclick=()=>{const k=localDate(now()).slice(0,7);if(k===state.viewMonth)return;const [y,m]=k.split('-').map(Number),cur=state.viewMonth.split('-').map(Number);moveMonth((y-cur[0])*12+(m-cur[1]))};
  document.querySelectorAll('[data-recent-tab]').forEach(b=>b.onclick=()=>{state.recentTab=b.dataset.recentTab;document.querySelectorAll('[data-recent-tab]').forEach(x=>x.classList.toggle('active',x===b));renderRecentHome()})
}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
function bindActions(){$('refreshBtn').onclick=refreshAll;$('clockInBtn').onclick=clock;$('clockOutBtn').onclick=clock;$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));$('saveSettings').onclick=saveSettings;$('openNotifyCenter').onclick=()=>window.GQ_NOTIFICATIONS?.openCenter()}

async function clock(){const n=nextAction(state.data.today);if(n==='none')return;try{const r=await call('clockAction',{}, {title:'正在寫入打卡…',text:'請稍後，完成後會自動更新'});applyLog(r.log);renderAll();navigator.vibrate?.(30);toast(r.action+'完成');if(r.requiresBreak)setTimeout(openBreakChoice,150)}catch(e){}}
function applyLog(log){if(!log)return;state.data.today=log;const idx=state.data.monthLogs.findIndex(x=>x.date===log.date);if(idx>=0)state.data.monthLogs[idx]=log;else if(log.date.startsWith(state.viewMonth))state.data.monthLogs.push(log);state.data.monthLogs.sort((a,b)=>a.date.localeCompare(b.date));state.monthCache.set(state.viewMonth,state.data.monthLogs.slice());const ridx=state.data.recentLogs.findIndex(x=>x.date===log.date);if(ridx>=0)state.data.recentLogs[ridx]=log;else state.data.recentLogs.unshift(log)}

function openAction(type){if(type==='manual')editForm(null);if(type==='editToday')editForm(state.data.today);if(type==='advance')advanceForm();if(type==='budget')budgetForm();if(type==='leave')editForm(Object.assign({},state.data.today,{dayStatus:'上午請假'}));if(type==='break')editForm(Object.assign({},state.data.today,{dayStatus:'休假'}))}
window.showModal=showModal;
function showModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.add('show')}
window.closeModal=closeModal;
function closeModal(){$('modal').classList.remove('show');clearInterval(state.breakTick)}
function editForm(log){const d=log||{date:localDate(now()),dayStatus:'正常上班'};showModal(log?'調整工時／請假':'補登工時',`<div class="modal-form"><label class="form-field">日期<input id="fDate" type="date" value="${d.date}"></label><label class="form-field">出勤狀態<select id="fStatus">${['正常上班','上午請假','下午請假','全天請假','休假'].map(x=>`<option ${d.dayStatus===x?'selected':''}>${x}</option>`).join('')}</select></label><div class="two"><label class="form-field">上午上班<input id="fAS" type="time" value="${shortValue(d.amStart)}"></label><label class="form-field">上午下班<input id="fAE" type="time" value="${shortValue(d.amEnd)}"></label></div><div class="two"><label class="form-field">下午上班<input id="fPS" type="time" value="${shortValue(d.pmStart)}"></label><label class="form-field">下午下班<input id="fPE" type="time" value="${shortValue(d.pmEnd)}"></label></div><div class="two"><label class="form-field">休息分鐘<input id="fBreak" type="number" value="${d.breakMinutes||0}"></label><label class="form-field">假別<select id="fLeave"><option value="">無</option>${['事假','病假','特休','公假'].map(x=>`<option ${d.leaveType===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label class="form-field">請假時數<input id="fLeaveH" type="number" step="0.5" value="${d.leaveHours||0}"></label><label class="form-field">備註<textarea id="fNote" rows="3">${esc(d.note||'')}</textarea></label><button id="saveWork" class="primary wide">儲存</button></div>`);$('saveWork').onclick=async()=>{const p={date:$('fDate').value,dayStatus:$('fStatus').value,amStart:$('fAS').value,amEnd:$('fAE').value,pmStart:$('fPS').value,pmEnd:$('fPE').value,breakMinutes:$('fBreak').value,leaveType:$('fLeave').value,leaveHours:$('fLeaveH').value,note:$('fNote').value};try{const r=await call('saveWorkLog',p,{title:'正在儲存工時…',text:'正在更新工時與薪資統計'});applyLog(r.log);closeModal();renderAll();toast('工時已更新')}catch(e){}}}
function shortValue(t){return t?t.slice(0,5):''}
function openDay(date){const r=state.data.monthLogs.find(x=>x.date===date)||state.data.recentLogs.find(x=>x.date===date);if(!r){showModal(date,`<div class="notice">這一天目前沒有紀錄。</div><button id="addDay" class="primary wide">新增此日紀錄</button>`);$('addDay').onclick=()=>editForm({date,dayStatus:'正常上班'});return}showModal(`${date} 紀錄`,`<div class="modal-form"><div class="record-item"><span>出勤狀態</span><b>${esc(r.dayStatus)}</b></div><div class="record-item"><span>上午原始</span><b>${short(r.amStart)} - ${short(r.amEnd)}</b></div><div class="record-item"><span>休息</span><b>${short(r.breakStart)} - ${short(r.breakEnd)}・${Number(r.breakMinutes||0)} 分</b></div><div class="record-item"><span>下午原始</span><b>${short(r.pmStart)} - ${short(r.pmEnd)}</b></div><div class="record-item"><span>有效計薪工時</span><b>${hoursText(r.totalHours)}</b></div><div class="record-item"><span>薪資</span><b class="green">$${fmt2(r.pay)}</b></div><button id="editDay" class="primary wide">編輯這一天</button></div>`);$('editDay').onclick=()=>editForm(r)}
function advanceForm(){showModal('新增預支',`<div class="modal-form"><label class="form-field">日期<input id="aDate" type="date" value="${localDate(now())}"></label><label class="form-field">金額<input id="aAmt" type="number" inputmode="decimal"></label><label class="form-field">備註<textarea id="aNote" rows="3" placeholder="例如：生活費、交通費"></textarea></label><div class="notice">預支會持續列入扣除，直到你自行刪除。</div><button id="saveAdvance" class="primary wide">儲存預支</button></div>`);$('saveAdvance').onclick=async()=>{try{const r=await call('saveAdvance',{date:$('aDate').value,amount:$('aAmt').value,note:$('aNote').value},{title:'正在新增預支…',text:'正在更新可用薪資'});state.data.monthAdvances.push(r.advance);state.data.recentAdvances.unshift(r.advance);closeModal();renderAll();toast('預支已新增')}catch(e){}}}
function budgetForm(){showModal('新增支出規劃',`<div class="modal-form"><label class="form-field">類別<select id="bCat"><option>房租</option><option>水電</option><option>車貸</option><option>保險</option><option>生活費</option><option>其他</option></select></label><label class="form-field">金額<input id="bAmt" type="number" inputmode="decimal"></label><label class="form-field">備註<textarea id="bNote" rows="3"></textarea></label><div class="notice">支出規劃不按月份歸零，刪除後才會停止扣除。</div><button id="saveBudget" class="primary wide">加入規劃</button></div>`);$('saveBudget').onclick=async()=>{try{const r=await call('saveBudget',{category:$('bCat').value,amount:$('bAmt').value,note:$('bNote').value},{title:'正在新增支出…',text:'正在更新支出規劃'});state.data.monthBudgets.push(r.budget);state.data.budgets.unshift(r.budget);closeModal();renderAll();toast('支出已新增')}catch(e){}}}
window.deleteAdvance=async id=>{if(!confirm('刪除此筆預支？'))return;try{const r=await call('deleteAdvance',{rowId:id},{title:'正在刪除預支…',text:'請稍後'});state.data.monthAdvances=r.advances;state.data.recentAdvances=r.advances.slice().reverse();renderAll();toast('預支已刪除')}catch(e){}};
window.deleteBudget=async id=>{if(!confirm('刪除此筆支出？'))return;try{const r=await call('deleteBudget',{rowId:id},{title:'正在刪除支出…',text:'請稍後'});state.data.monthBudgets=r.budgets;state.data.budgets=r.budgets.slice().reverse();renderAll();toast('支出已刪除')}catch(e){}};
window.toggleBudget=async(id,paid)=>{try{const r=await call('toggleBudgetPaid',{rowId:id,paid},{title:'正在更新狀態…',text:'請稍後'});state.data.monthBudgets=state.data.monthBudgets.map(x=>x.rowId===r.rowId?{...x,status:r.status}:x);state.data.budgets=state.data.budgets.map(x=>x.rowId===r.rowId?{...x,status:r.status}:x);renderAll();toast('狀態已更新')}catch(e){}};
async function saveSettings(){try{const p={hourlyRate:$('setRate').value,payday:$('setPayday').value,monthlyGoal:$('setGoal').value,syncSeconds:$('setSync').value,defaultBreakMinutes:$('setBreak').value,scheduledStart:$('setStart').value,scheduledEnd:$('setEnd').value},r=await call('saveSettings',p,{title:'正在儲存設定…',text:'若時薪有變更，會同步重新計算歷史薪資'});state.data.settings=r.settings;state.data.today=r.today;state.viewMonth=r.viewMonth;state.data.viewMonth=r.viewMonth;state.data.monthLogs=r.monthLogs||[];state.monthCache.clear();state.monthCache.set(state.viewMonth,state.data.monthLogs.slice());renderAll();scheduleSync();toast('設定已儲存')}catch(e){}}

function openBreakChoice(){showModal('設定休息時間',`<div class="modal-form"><div style="text-align:center"><h3>辛苦了，先休息一下 ☕</h3><p style="color:var(--muted);font-size:11px">選擇休息時間，會自動算出回班時間。</p></div><div class="two"><button class="primary" id="b30">30 分鐘</button><button class="primary" id="b60">1 小時</button></div><label class="form-field">自訂分鐘<input id="customBreak" type="number" value="${state.data.settings.defaultBreakMinutes}"></label><button id="bCustom" class="primary wide">開始休息</button></div>`);$('b30').onclick=()=>saveBreak(30);$('b60').onclick=()=>saveBreak(60);$('bCustom').onclick=()=>saveBreak(Number($('customBreak').value))}
async function saveBreak(minutes){try{const r=await call('saveBreak',{date:state.data.today.date,start:state.data.today.amEnd,minutes},{title:'正在設定休息時間…',text:'正在計算回班時間'});applyLog(r.log);renderAll();showBreakCountdown();toast('休息時間已設定')}catch(e){}}
function breakActive(){const d=state.data?.today;return !!(d?.breakEnd&&!d.pmStart&&now()<td(d.date,d.breakEnd))}
function renderBreakStrip(){const d=state.data.today,el=$('breakStrip');if(!breakActive()){el.classList.add('hidden');$('breakHint').textContent='';return}el.classList.remove('hidden');const end=td(d.date,d.breakEnd),start=td(d.date,d.breakStart),left=Math.max(0,Math.floor((end-now())/1000)),total=Math.max(1,(end-start)/1000);$('breakUntil').textContent=d.breakEnd.slice(0,5);$('breakRemain').textContent='剩餘 '+dur(left).slice(3);$('breakRemain').style.color=left<=300?'var(--red)':'var(--blue)';$('breakBar').style.width=Math.min(100,Math.max(0,(1-left/total)*100))+'%';$('breakHint').textContent=`休息中 ${dur(left).slice(3)}`}
function showBreakCountdown(){clearInterval(state.breakTick);const d=state.data.today;showModal('休息時間',`<div style="text-align:center;padding:10px"><img src="./assets/logo.svg" style="width:62px;height:62px"><p style="color:var(--muted);font-size:11px">補充能量，等等繼續加油！</p><div style="font-size:13px">休息至</div><div id="modalBreakUntil" style="font-size:44px;color:var(--green);font-weight:850">${d.breakEnd.slice(0,5)}</div><div id="modalBreakCount" style="font-size:27px;font-weight:800;margin:15px 0">--:--</div><div class="mini-progress"><i id="modalBreakBar"></i></div><p id="backHint" style="color:var(--muted);font-size:10px"></p></div><button class="pill-btn wide" onclick="closeModal()">暫時關閉</button>`);const start=td(d.date,d.breakStart),end=td(d.date,d.breakEnd);function run(){const left=Math.max(0,Math.floor((end-now())/1000)),total=Math.max(1,(end-start)/1000);$('modalBreakCount').textContent=dur(left);$('modalBreakCount').style.color=left<=300?'var(--red)':'white';$('modalBreakBar').style.width=Math.min(100,Math.max(0,(1-left/total)*100))+'%';const ret=new Date(end-5*60000);$('backHint').textContent=`${String(ret.getHours()).padStart(2,'0')}:${String(ret.getMinutes()).padStart(2,'0')} 記得回來準備打卡`;if(left<=0){clearInterval(state.breakTick);$('modalBreakCount').textContent='休息結束';navigator.vibrate?.([100,80,100])}}run();state.breakTick=setInterval(run,1000)}

async function refreshAll(){showBusy('正在更新資料…','請稍後');try{const r=await GQ_API.call('getAppData',{viewMonth:state.viewMonth});state.data=r;state.viewMonth=r.viewMonth;state.version=r.version||state.version;state.offset=new Date(r.serverNow).getTime()-Date.now();state.monthCache.set(r.viewMonth,(r.monthLogs||[]).slice());renderAll();setSync('已同步');toast('資料已更新')}catch(e){showError(e.message)}finally{hideBusy()}}
function scheduleSync(){clearInterval(state.syncTimer);const sec=Math.max(15,Number(state.data.settings.syncSeconds||15));state.syncTimer=setInterval(async()=>{try{const r=await GQ_API.call('getSyncState',{lastVersion:state.version},10000);if(r.changed){const full=await GQ_API.call('getAppData',{viewMonth:state.viewMonth},20000);state.data=full;state.viewMonth=full.viewMonth;state.version=full.version;state.offset=new Date(full.serverNow).getTime()-Date.now();state.monthCache.set(full.viewMonth,(full.monthLogs||[]).slice());renderAll()}setSync('已同步')}catch(e){setSync('稍後重試',false)}},sec*1000)}

boot();
